# Threshold when a diamond find rate is considered as suspicious.
suspicious-threshold: 0.8

# Executes a command if someone is acting suspicious. Set to "" to disable, do not include the "/" character.
# Available placeholders: %player%
# Example: "say This is an example command!"
suspicious-command: ""

# Should diamond finds be logged into a separate file as well?
logger: true